baseurl: https://viralkindness.cards/
languageCode: en-US
title: "Viral Kindness Cards"
theme: senzilla
relativeURLs: true

contentdir: content
datadir: data
layoutdir: layouts
publishdir: public

params:
  author: Dick Olsson

languages:
  en:
    languageName: English
    languageCode: en-US
    weight: 1
    params:
      description: Viral kindness cards to help your neighbour with COVID-19
      keywords: neighbour, viral, kindness, help, corona, covid19
      footer: "Contribute to this website: https://github.com/dickolsson/viralkindness"
  fr:
    languageName: Français
    languageCode: fr-FR
    weight: 2
    params:
      description: Cartes de gentillesse virale pour aider votre voisin avec COVID-19
      keywords: voisin, viral, gentillesse, aide, corona, covid19
      footer: "Contribuez à ce site: https://github.com/dickolsson/viralkindness"
  es:
    languageName: Español
    languageCode: es-ES
    weight: 3
    params:
      description: Tarjetas de amabilidad viral para ayudar a tu vecina con COVID-19
      keywords: vecina, viral, amabilidad, ayuda, corona, covid19
      footer: "Contribuir a este sitio web: https://github.com/dickolsson/viralkindness"
  de:
    languageName: Deutsch
    languageCode: de-DE
    weight: 4
    params:
      description: Virale Gütekarten, um Ihrem Nachbarn mit COVID-19 zu helfen
      keywords: nachbar, viral, freundlichkeit, hilfe, corona, covid19
      footer: "Contribuir a este sitio web: https://github.com/dickolsson/viralkindness"